'couse page'
Bereket234/ESSS-learning-platform pull request #9
Opened 2023-12-22 09:02 UTC by donnebiyu0

<img width="960" alt="image" src="https://github.com/Bereket234/ESSS-learning-platform/assets/80168589/9991ed72-49dc-4a8d-b659-79f6c924508f">

2023-12-22 12:36 UTC, Joephy527 requested changes
no need to import react from react so remove those

no need for white color to be configured in the tailwind config file because it already exists in tailwind, that should also be removed

Course.tsx shouldn't be in the root app directory move it into components folder

move all the interfaces you defined into the types folder, also better to use "type" than "interface" to define object shapes

don't write css specific to a component in the globals.css file move those in to css module files specific to the components, only universal styles like fonts should be in the globals file. also try to write as much css in tailwind before using plain css and try avoiding important tag in css

remove unused code commented out and add some comments here and there for readability

you've added daisyui as a dependency but haven't used it.

2024-02-04 19:09 UTC, Joephy527 commented on app/components/Course.tsx
>  interface CourseProps {
move this type to the types folder as well

2024-02-04 19:11 UTC, Joephy527 reviewed
move your types from the dynamic-courses folder into their own folder in the types folder and create a types.ts file there

2024-03-20 20:27 UTC, BrookW-83 commented on app/courses/page.tsx
the pages file should't containe this many code you should finsh all the code inside the components and import the inside the page.tsx , the page.tsx file should all be a place to import your component and not handle any logic inside,

2025-10-31 15:29 UTC, closed without merging